name: Protección de la rama main
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Diario a medianoche UTC

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Obtiene y protege repositorios
        uses: actions/github-script@v6
        with:
          script: |
            const ORG_NAME = 'iescastillodeluna';

            const { data: repos } = await github.rest.repos.listForOrg({
              org: ORG_NAME,
              type: 'all',
            });

            for (const repo of repos) {
              try {
                // Obtener el primer commit del repositorio
                const { data: commits } = await github.rest.repos.listCommits({
                  owner: ORG_NAME,
                  repo: repo.name,
                  per_page: 1,
                  page: 1,
                });

                if (commits.length === 0) continue;  # Saltar repos vacíos

                const firstCommitAuthor = commits[0].author.login;
                if (firstCommitAuthor === 'github-classroom[bot]') {
                  await github.rest.repos.updateBranchProtection({
                    owner: ORG_NAME,
                    repo: repo.name,
                    branch: 'main',
                    required_status_checks: null,
                    enforce_admins: true,
                    required_pull_request_reviews: {
                      required_approving_review_count: 1,
                    },
                    restrictions: null,
                  });
                  console.log(`Protegido: ${repo.name}`);
                }
              } catch (error) {
                console.error(`Error en ${repo.name}: ${error.message}`);
              }
            }
